stages:
  - tests

test:
  stage: tests
  before-script:
    - docker run -v %cd%/:/opt/project -w="/opt/project" composer composer install --no-interaction
  script:
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - docker run -v %cd%:/PHP -v %cd%/Settings/servercreds.json:/servercreds.json -v %cd%/TestData:/TestData -w="/PHP" --rm php:7.2.2 vendor/bin/phpunit -c phpunit.xml 
  artifacts:
    paths:
      - 'testReports/logfile.xml'

