stages:
  - build
  - tests
  - publishing
  - retest
  - tag_version

build: 
  stage: build
  script: 
    - 'docker run -v $PWD/:/opt/project -w="/opt/project" composer /bin/bash -c "composer install --no-interaction; chmod 777 -R vendor/"'
  tags:
  - awcloud-linux


unit-tests:
  stage: tests
  before_script:
    - 'docker run -v $PWD/:/opt/project -w="/opt/project" composer /bin/bash -c "composer install --no-interaction; chmod 777 -R vendor/"'
  script:
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - 'docker run -v $PWD:/PHP -v $PWD/Settings/servercreds.json:/servercreds.json -v $PWD/TestData:/TestData -w="/PHP" --rm php:7.2.2 /bin/bash -c "vendor/bin/phpunit -c phpunit.xml; chmod 777 -R vendor/ testReports/"'
  artifacts:
    paths:
      - 'testReports/logfile.xml'
  tags:
    - awcloud-linux

bdd-tests:
  stage: tests
  before_script:
    - 'docker run -v $PWD/:/opt/project -w="/opt/project" composer /bin/bash -c "composer install --no-interaction; chmod 777 -R vendor/"'
  script:
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - 'docker run -v %cd%:/PHP -v %cd%/Settings/servercreds.json:/servercreds.json -v %cd%/TestData:/TestData -w="/PHP" --rm php:latest /bin/bash -c "vendor/bin/behat --config=behat.yml --format=junit --out=testReports/bdd; chmod 777 -R vendor/ testReports/"'
  artifacts:
    paths:
      - 'testReports/bdd/*.xml'
  tags:
    - awcloud-linux

merge-to-testPackage:
  stage: publishing
  before_script:
    - $env:ORIGIN += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-php.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
  script: 
    - git checkout master
    - 'git remote set-url origin $env:ORIGIN'
    - git checkout testPackage1
    - git reset --hard origin/testPackage1
    - git merge --no-ff --allow-unrelated-histories origin/master
    - git diff --name-status
    - git push
  only: 
    - WORDSCLOUD-793
  tags: 
    - awcloud
  when: manual

publish_package:
  stage: publishing
  only: 
    - testPackage1
  before_script:
    - $env:ORIGIN += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-php.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
    - docker build -f ./docker/latest/Dockerfile -t asposewordsphp:latest
  script:
    - docker run -v $PWD/:/app -w="/app" asposewordsphp:latest php composer.phar install && php composer.phar update aspose/words-sdk-php --no-interaction
    - git diff --name-status
    - git ls-files --others --exclude-standard
    - git add -A
    - git commit -am "new version of package referenced for tests"
    - git push $env:ORIGIN testPackage1

retest:
  stage: retest
  script:
    - mkdir -p Settings
    - echo "{\"AppSid\":\"$WordsAppSid\",\"AppKey\":\"$WordsAppKey\",\"BaseUrl\":\"$WordsBaseUrl\" }" > Settings/servercreds.json
    - docker run -v $PWD:/PHP -v $PWD/Settings/servercreds.json:/servercreds.json -v $PWD/TestData:/TestData -w="/PHP" --rm php:7.2.2 vendor/bin/phpunit -c phpunit.xml && chmod 777 -R vendor/ testReports/
    - docker run -v $PWD/:/app -w="/app" --rm php -dmemory_limit=1G ./vendor/bin/phpcs -s --report-file=testReports/codeStyleErrors ./src ./features/bootstrap
  artifacts:
    paths:
      - 'testReports/logfile.xml'
      - 'testReports/codeStyleErrors.xml'
  tags:
    - awcloud-linux
  only:
    - testPackage1

add version tag:
  stage: tag_version
  only:
    - testPackage1
  before_script:
    - $env:ORIGIN += 'https://{0}:{1}@git.auckland.dynabic.com/words-cloud/words-cloud-php.git' -f $env:GIT_CI_USER, $env:GIT_CI_PASS
    - $env:SDK_VERSION += ((Get-Date).AddMonths(1)).tostring("yy.M")
  script: 
    - git tag -a $env:SDK_VERSION -m 'version $env:SDK_VERSION' | exit 0
    - git push $env:ORIGIN $env:SDK_VERSION 



